### PR TITLE
Move MinKNOW reports to ngi-internal instead of embedding in StatusDB doc

### PR DESCRIPTION
**Pull request by kedhammar**
- taca.yaml on preproc1 modified with help of @aanil 
- New AM edition 1620:3 started to reflect changes

I don't have access to hiseq.bioinfo on preproc1, so I can't test it currently. I'll request this from IT.

### CODE REVIEW

**Review by aanil — APPROVED** [review]
👍 Looks ok!

**Comment by kedhammar** [comment]
Will merge once GenStat PR for showing reports at the new location is set up, and old reports are re-located.

**Review by ssjunnebo — APPROVED** [review]
Looks good 👍 Can you bump the version as well? Makes deploying it on preproc easier.

**Comment by kedhammar** [comment]
Linked to https://github.com/SciLifeLab/genomics-status/pull/728

**Pull request merged**
