### PR TITLE
point to sll instead of me

### PR DESCRIPTION
**Pull request by Galithil**
Depends on https://github.com/SciLifeLab/flowcell_parser/pull/1.
Once the other one is merged, this one can be.

### CODE REVIEW

**Comment by Galithil** [comment]
Also, the link is not working because of the last renamings, fix inside

**Comment by Galithil** [comment]
Any comments on this one ? linking the undetermined files will not work until this is merged...

**Comment by remiolsen** [comment]
Nope :+1:

**Comment by Galithil** [comment]
thanks. i'll deploy

**Pull request merged**
