### PR TITLE
Removing automate soflinking of Undet in X-runs

### PR DESCRIPTION
**Pull request by vezzi**
We no longer automatically softlink undetermined reads when a single sample per lane is run.
In case we need to use undet we will manually softlink them.

### CODE REVIEW

**Comment by vezzi** [comment]
@Galithil and @parlundin have a look please

**Comment by vezzi** [comment]
@Galithil @kate-v-stepanova can you review this and marge? thanks

**Comment by Galithil** [comment]
okay then, looks fine.

**Comment by vezzi** [comment]
Ok... you know what... I am sick of waiting for someone merging my pool request!!!!!

**Comment by Galithil** [comment]
I reviewed.

**Comment by Galithil** [comment]
Also, you can have as many pools as you want, just make sure you don't keep them filled in the winter.

**Pull request merged**
