### PR TITLE
Add support for Smart-seq index sets

### PR DESCRIPTION
**Pull request by chuan-wang**

### CODE REVIEW

**Review by ssjunnebo — APPROVED** [review]
Very nice! 👍

**Comment by ssjunnebo** [comment]
Oh, some tests seem to be failing. Would you mind having a look at those before I merge? 🙂

**Comment by chuan-wang** [comment]
OK Thanks! I will look into it. /chuan

**Comment by ssjunnebo** [comment]
Awesome job fixing those tests! 😄 Looks good, I'll go ahead and merge 👍

**Pull request merged**
